name: Test integration

on:
  pull_request:
    branches:
        - main
  workflow_dispatch:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.11"
          cache: "pip"

      - name: install compliance-trestle
        run: pip install compliance-trestle==3.4.0

      - name: SDK Conformance Test
        uses: ./actions/conformance
        with:
          entrypoint: trestle